collector:
  snippets:
    enabled: false

bering:
  enabled: true
  image:
    tag: "v0.3.2"
    digest: "sha256:98e443461bf59d92cc19b20f425602de91b22a272ecd9a79df5cc20f96c735a8"
  service:
    publicName: bering-discovery

sheaft:
  enabled: true
  image:
    tag: "v0.2.2"
    digest: "sha256:df6a7bbf21e4f307d1d33425f4245eeb34f5d051f46b8ad36ad536b33bf2c331"
  service:
    publicName: sheaft-reports

prometheusScrapeHooks:
  enabled: false

grafanaDashboards:
  enabled: false
