collector:
  snippets:
    enabled: false

bering:
  enabled: true
  image:
    tag: "v0.3.2"
    digest: "sha256:98e443461bf59d92cc19b20f425602de91b22a272ecd9a79df5cc20f96c735a8"
  service:
    publicName: bering-discovery

sheaft:
  enabled: true
  image:
    tag: "v0.2.3"
    digest: "sha256:07bca0e01ef0bfb09c9561c2883d7acf7b2ee6374be373ecd0168747da9f1e76"
  service:
    publicName: sheaft-reports

prometheusScrapeHooks:
  enabled: false

grafanaDashboards:
  enabled: false
