receivers:
  prometheus/mb3r:
    config:
      scrape_configs:
        - job_name: "mb3r-bering"
          metrics_path: /metrics
          static_configs:
            - targets:
                - ${BERING_METRICS_TARGET:mb3r-otel-addon-bering:4318}
        - job_name: "mb3r-sheaft"
          metrics_path: /metrics
          static_configs:
            - targets:
                - ${SHEAFT_METRICS_TARGET:mb3r-otel-addon-sheaft:8080}
