nameOverride: ""
fullnameOverride: ""

global:
  imageRegistry: ""
  imagePullSecrets: []
  commonLabels: {}
  commonAnnotations: {}

bundleMetadata:
  enabled: true

collector:
  existingDeployment: ""
  targetEndpoint: ""
  snippets:
    enabled: false
    name: ""
    includeMetricsPipeline: true
    includeLogsPipeline: true
    includeTracesPipeline: true
    includePrometheusReceiver: false
    tlsInsecure: true

bering:
  enabled: false
  replicaCount: 1
  image:
    registry: ""
    repository: "ghcr.io/mb3r-lab/bering"
    tag: "v0.1.0"
    digest: "sha256:8e8ce6599b43477b0653617e829d41c62a3189d16b60ecb424cca718fc0e2674"
    pullPolicy: IfNotPresent
  extraArgs: []
  env: []
  resources: {}
  service:
    type: ClusterIP
    port: 4317
    metricsPort: 9464
    annotations: {}
  prometheus:
    annotations: {}
  serviceMonitor:
    enabled: false
    interval: 30s
    labels: {}

sheaft:
  enabled: false
  replicaCount: 1
  image:
    registry: ""
    repository: "ghcr.io/mb3r-lab/sheaft"
    tag: "v0.1.1"
    digest: "sha256:eb1ebf9d96c55c5bb29e226e07496d152eb3a66b52dd9d34ba799fa4aef70624"
    pullPolicy: IfNotPresent
  extraArgs: []
  env: []
  resources: {}
  service:
    type: ClusterIP
    port: 8080
    metricsPort: 9465
    annotations: {}
  prometheus:
    annotations: {}
  serviceMonitor:
    enabled: false
    interval: 30s
    labels: {}

prometheusScrapeHooks:
  enabled: false
  renderConfigMap: true
  additionalLabels: {}
  jobNames:
    bering: "mb3r-bering"
    sheaft: "mb3r-sheaft"

grafanaDashboards:
  enabled: false
  providerName: "mb3r-stack"
  folder: "MB3R"
  labelKey: "grafana_dashboard"
  labelValue: "1"
  existingConfigMaps: []
