fullnameOverride: mb3r-otel-addon

collector:
  snippets:
    enabled: true
    includePrometheusReceiver: true

bering:
  enabled: true

sheaft:
  enabled: true
  coLocateWithBering: true

prometheusScrapeHooks:
  enabled: true

grafanaDashboards:
  enabled: true
  existingConfigMaps:
    - mb3r-bering-dashboard-v1-0-0
    - mb3r-sheaft-dashboard-v1-0-0
