{{- if and (eq .Values.artifacts.volume.type "persistentVolumeClaim") (not .Values.artifacts.volume.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mb3r-stack.artifactPVCName" . }}
  labels:
    {{- include "mb3r-stack.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.artifacts.volume.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.artifacts.volume.size }}
  {{- with .Values.artifacts.volume.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
