{{- if and .Values.bering.enabled .Values.bering.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mb3r-stack.fullname" . }}-bering
  labels:
    {{- include "mb3r-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: bering
    {{- with .Values.bering.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "mb3r-stack.selectorLabels" . | nindent 6 }}
      mb3r.io/has-bering: "true"
      mb3r.io/service-role: primary
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.bering.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.bering.serviceMonitor.scrapeTimeout }}
---
{{- end }}
{{- if and .Values.sheaft.enabled .Values.sheaft.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mb3r-stack.fullname" . }}-sheaft
  labels:
    {{- include "mb3r-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: sheaft
    {{- with .Values.sheaft.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "mb3r-stack.selectorLabels" . | nindent 6 }}
      mb3r.io/has-sheaft: "true"
      mb3r.io/service-role: primary
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.sheaft.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.sheaft.serviceMonitor.scrapeTimeout }}
{{- end }}
