collector:
  snippets:
    enabled: true
    includePrometheusReceiver: true

bering:
  enabled: true
  image:
    tag: "v0.1.0"
    digest: "sha256:8e8ce6599b43477b0653617e829d41c62a3189d16b60ecb424cca718fc0e2674"

sheaft:
  enabled: true
  image:
    tag: "v0.1.1"
    digest: "sha256:eb1ebf9d96c55c5bb29e226e07496d152eb3a66b52dd9d34ba799fa4aef70624"

prometheusScrapeHooks:
  enabled: true

grafanaDashboards:
  enabled: true
  existingConfigMaps:
    - mb3r-bering-dashboard-v1-0-0
    - mb3r-sheaft-dashboard-v1-0-0
