{{- if .Values.bundleMetadata.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mb3r-otel-addon.fullname" . }}-bundle-metadata
  labels:
    {{- include "mb3r-otel-addon.labels" . | nindent 4 }}
data:
  stack-name: "mb3r-stack"
  chart-name: {{ .Chart.Name | quote }}
  chart-version: {{ .Chart.Version | quote }}
  collector-existing-deployment: {{ .Values.collector.existingDeployment | quote }}
  bering-enabled: {{ .Values.bering.enabled | quote }}
  sheaft-enabled: {{ .Values.sheaft.enabled | quote }}
  repo-role: "integration-layer"
{{- end }}
