global:
  imageRegistry: "registry.example.com/observability"

collector:
  existingDeployment: "otel-collector"
  targetEndpoint: "http://bering-discovery.observability.svc.cluster.local:4318"
  snippets:
    enabled: true
    tlsInsecure: true

bering:
  enabled: true
  image:
    repository: "mb3r-lab/bering"
    tag: "v0.3.1"
    digest: "sha256:ac960e908df7fb7defb4ce950d2e54ff8d8f65f7cd5e5f723d424cb425248bad"
  service:
    publicName: bering-discovery
  serviceMonitor:
    enabled: true

sheaft:
  enabled: true
  image:
    repository: "mb3r-lab/sheaft"
    tag: "v0.2.1"
    digest: "sha256:543771ca12722147578bf7a99dd07c5477c7fe15e7404cf6659a2a02f203a93b"
  service:
    publicName: sheaft-reports
  serviceMonitor:
    enabled: true

prometheusScrapeHooks:
  enabled: true

grafanaDashboards:
  enabled: true
  providerName: "mb3r-prod"
  existingConfigMaps:
    - mb3r-bering-dashboard-v1-0-0
    - mb3r-sheaft-dashboard-v1-0-0
