global:
  imageRegistry: "registry.example.com/observability"

collector:
  existingDeployment: "otel-collector"
  targetEndpoint: "http://bering-discovery.observability.svc.cluster.local:4318"
  snippets:
    enabled: true
    tlsInsecure: true

bering:
  enabled: true
  image:
    repository: "mb3r-lab/bering"
    tag: "v1.0.0"
    digest: "sha256:1da482d2629f695e0109525fb9c27e1fd8c502da85af4bbae95ddb176969c3d5"
  service:
    publicName: bering-discovery
  serviceMonitor:
    enabled: true

sheaft:
  enabled: true
  image:
    repository: "mb3r-lab/sheaft"
    tag: "v1.0.0"
    digest: "sha256:195e38b6c4cf4e8cfab1d4ef86083bf9511c46e0617682d74b6768e43a4c9a07"
  service:
    publicName: sheaft-reports
  serviceMonitor:
    enabled: true

prometheusScrapeHooks:
  enabled: true

grafanaDashboards:
  enabled: true
  providerName: "mb3r-prod"
  existingConfigMaps:
    - mb3r-bering-dashboard-v1-0-0
    - mb3r-sheaft-dashboard-v1-0-0
