global:
  imageRegistry: "registry.example.com/observability"

collector:
  existingDeployment: "otel-collector"
  targetEndpoint: "http://bering-discovery.observability.svc.cluster.local:4318"
  snippets:
    enabled: true
    tlsInsecure: true

bering:
  enabled: true
  image:
    repository: "mb3r-lab/bering"
    tag: "v0.3.4"
    digest: "sha256:a825e7eb7d8a97610dd22cfea725e747e5b77f27663ed2972ac2978ee60d392d"
  service:
    publicName: bering-discovery
  serviceMonitor:
    enabled: true

sheaft:
  enabled: true
  image:
    repository: "mb3r-lab/sheaft"
    tag: "v0.2.4"
    digest: "sha256:a434b5fb3f034a58455b20fa27a6976aa79d66340814f4cd81549b20bd8a5db8"
  service:
    publicName: sheaft-reports
  serviceMonitor:
    enabled: true

prometheusScrapeHooks:
  enabled: true

grafanaDashboards:
  enabled: true
  providerName: "mb3r-prod"
  existingConfigMaps:
    - mb3r-bering-dashboard-v1-0-0
    - mb3r-sheaft-dashboard-v1-0-0
