from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

from common import DIST, ROOT, check, stack_manifest


def generated_release_notes(version: str, status: str) -> str:
    qualifier = {
        "draft": "draft integration bundle",
        "candidate": "candidate integration bundle",
        "ga": "integration bundle",
        "deprecated": "deprecated integration bundle",
    }[status]
    return (
        f"## mb3r-stack v{version}\n\n"
        f"Autogenerated notes for the {qualifier}. Curate `release/v{version}.md` to replace this body.\n"
    )


def stage_release_metadata(output_dir: Path) -> list[Path]:
    manifest = stack_manifest()
    version = manifest["stack"]["version"]
    status = manifest["stack"]["status"]

    output_dir.mkdir(parents=True, exist_ok=True)

    notes_source = ROOT / "release" / f"v{version}.md"
    notes_target = output_dir / "release-notes.md"
    if notes_source.exists():
        shutil.copyfile(notes_source, notes_target)
    else:
        notes_target.write_text(generated_release_notes(version, status), encoding="utf-8")

    schema_source = ROOT / "schemas" / "release-manifest.schema.json"
    schema_target = output_dir / "release-manifest.schema.json"
    shutil.copyfile(schema_source, schema_target)

    chart_package = output_dir / "charts" / manifest["artifacts"]["chart"]["package"]
    asset_archive = output_dir / "assets" / manifest["artifacts"]["assetPack"]["archive"]
    check(chart_package.exists(), f"Missing chart package {chart_package.relative_to(ROOT)}")
    check(asset_archive.exists(), f"Missing asset archive {asset_archive.relative_to(ROOT)}")

    assets = [
        chart_package.relative_to(output_dir).as_posix(),
        asset_archive.relative_to(output_dir).as_posix(),
        "stack-manifest.json",
        "compatibility-matrix.json",
        "release-manifest.json",
        "release-manifest.schema.json",
        "release-notes.md",
        "SHA256SUMS.txt",
        "sbom.cdx.json",
    ]
    assets_path = output_dir / "release-assets.txt"
    assets_path.write_text("\n".join(assets) + "\n", encoding="utf-8")
    return [notes_target, schema_target, assets_path]


def main() -> int:
    parser = argparse.ArgumentParser(description="Stage release notes, schema, and asset list into dist/.")
    parser.add_argument("--output-dir", default=str(DIST))
    args = parser.parse_args()

    files = stage_release_metadata(Path(args.output_dir))
    for path in files:
        print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
