collector:
  snippets:
    enabled: false

bering:
  enabled: true
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"

sheaft:
  enabled: true
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"

prometheusScrapeHooks:
  enabled: false

grafanaDashboards:
  enabled: false
